# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='品牌名称')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '品牌',
                'ordering': ['index'],
                'verbose_name': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('price', models.FloatField(default=0, verbose_name='原价')),
                ('discount', models.FloatField(default=0, verbose_name='折扣')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('desc', models.CharField(max_length=128, verbose_name='描述')),
                ('num', models.IntegerField(default=0, verbose_name='库存')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='product/%Y/%m', verbose_name='显示图片')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='image PPOI')),
                ('active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Brand', verbose_name='品牌')),
                ('categories', models.ManyToManyField(to='store.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '商品',
                'ordering': ['id'],
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'M'), (1, 'S'), (2, 'L')], verbose_name='尺寸')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '尺寸',
                'ordering': ['index'],
                'verbose_name': '尺寸',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='store.Size', verbose_name='大小'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='store.Tag', verbose_name='标签'),
        ),
    ]
