# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 22:55
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160709_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_back',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product/%Y/%m', verbose_name='显示图片'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_right',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product/%Y/%m', verbose_name='显示图片'),
        ),
    ]
