# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160711_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_back',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_right',
        ),
    ]
