# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 23:38
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160712_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product/%Y/%m', verbose_name='背部图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_right',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product/%Y/%m', verbose_name='侧面图片'),
        ),
    ]
